### ISSUE TITLE
The grid widget

### ISSUE THREAD

**Issue by ScottHuangZL** [Fulma/Fulma#148]
Can you leverage the Fulma elements to build a grid/table widget?
The reason is usually that is the most useful widget in web development.

Such as: https://ant.design/components/table/ 

Thanks.

**Comment by MangelMaxime** [comment]
For such things, you have the [table](https://mangelmaxime.github.io/Fulma/#fulma/elements/table) element.

Example taken from our production app (so I masked the sensitive data ^^)
<img width="1118" alt="capture d ecran 2018-05-21 a 17 36 47" src="https://user-images.githubusercontent.com/4760796/40316165-bed1feca-5d1d-11e8-8f5f-7578418d9f3c.png">

Are you speaking about being able to wrote this kind of display from scratch or having a datatable like component that take a source of data/columns and do the display for you ?

If that's the first then you can already do it.

For the second I am planning to add something like that into Fulma already tracked here #63 . Just need some time because I want to handle pagination support, probably search, sortable too. And this take time to do correctly.

**Comment by MangelMaxime** [comment]
For info, creating the datatable like component should be my work of the week now that Fulma is 100% mapped.

**Comment by ScottHuangZL** [comment]
@MangelMaxime Good to know you have the plan to create datatable widget.

The **https://ant.design/components/table/** is very powerful. Please try mimic it as much as possible. Such as header freeze, left columns / right columns freeze, filter, sort, pagination, export to excel and so on.

I am plan use Fulma/Elmish in production web in case the data table function ready, thanks.

Btw, another good sample for your reference is http://demos.krajee.com/  (Widgets for Yii2)

**Comment by MangelMaxime** [comment]
Thank you for the sample, I will try to port the API that make sense IMO.

And that can be supported by default by Bulma.

For example, in version 1 I will not support this example:
- https://ant.design/components/table/#components-table-demo-fixed-columns-header
  - This one because the display is really bad and hard to optimize
- https://ant.design/components/table/#components-table-demo-grouping-columns
  - Header groups aren't supported by Bulma as far as I know

**Comment by MangelMaxime** [comment]
@ScottHuangZL For info, if you want to use Ant instead of Fulma @evilz is working on [fable-ant-design](https://github.com/evilz/fable-ant-design). 

This is a binding directly on top of Ant design and so you should have the same features. The binding is still in WIP

**Comment by ScottHuangZL** [comment]
@MangelMaxime  thanks for your info.  Glad to know @evilz start working for the ant design binding.  But the most important widget datatable still not in current future, hope can see it soon.

I am agree you split Fulma datatable to different phase, the fixed columns need more time to work.
As for the grouping columns, you cannot fully depends on Bulma, instead, think about use the table/td and so on logic, thanks.
I agree these 2 features need some efforts to make it happen, may be version 1.1:)

Thanks again.
