### ISSUE TITLE
Docs: backwards compatible with FontAwesome 4 support

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#176]
Right now all documentation shows how to use the new Font Awesome icons, but it would be handy for people who still have an old version of Fulma to have a link to the previous icon page.

**Comment by selketjah** [comment]
@MangelMaxime Is this good for you that I add this?

**Comment by MangelMaxime** [comment]
In the current form of the documentation this is not possible to write documentation for different versions because the documentation itself is build using the library.

My idea, is to build the old documentation with a message at the top of the page saying this is the old documentation. Then host that version of the documentation in the `gh-pages` branch and add a link to it.

**Comment by MangelMaxime** [comment]
I am closing because it will probably never happen. And well, the release was more than 1 year ago.
