### ISSUE TITLE
Docs: not all switches are working

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#210]
The switches in sections `Colors`, `Sizes`, `Styles` and `States` are not working

Seeing how they work in the other sections of the switch documents, I think all of the switches are suppose to work.

https://fulma.github.io/Fulma/#fulma-extensions/switch

**Comment by MangelMaxime** [comment]
Hum, they are kind of static indeed because they are declared using:

```fs
Switch.Checked true
```

So, they are always `checked` that's why you can't `uncheck` them. But indeed, something can be improved here I think.

**Comment by alfonsogarciacaro** [comment]
State hook to the rescue!

**Comment by MangelMaxime** [comment]
I don't think it will be that simple, because I don't want the `hook` declaration to be visible in the "code preview".

But we can always use the standard stateful components that Fulma doc know how to use. And have all the switch control by a single bool. So when you switch one all are switched I have no real problem with that.

**Comment by MangelMaxime** [comment]
The documentation has been updated
