### ISSUE TITLE
Is it possible to combine *.Props into parent list?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Fulma/Fulma#214]
Hello there, 

I am playing with Bulma and Fulma lately and it seems that Bulma-specific properties are separated from HTML props. These Html props need to be provided separately using `*.Props` which looks very strange:
```fs
Button.button 
  [ Button.Color IsPrimary
    Button.Props [  OnClick (fun _ -> dispatch msg) ]  ]
  [ str "Click me" ]
``` 
This adds a lot of friction to the code with another nested list for every element! Where in reality I only need the *class names* to be type safe. 

I expected to be able to use `OnClick` as part of button:
```fs
Button.button 
  [ Button.Color IsPrimary
    Button.OnClick (fun _ -> dispatch msg)  ]
  [ str "Click me" ]
```
Are there any plans to implement such syntax? 

I have been testing simpler alternative syntax that only applies *classes*, nothing more, something "Fulma lite": 
```fs
type Bulma = 
  | Button
  | IsPrimary
  | IsMedium 
  | IsLoading of bool
  | (* etc. *)

let toBulmaClass= function 
  | Button -> "button"
  | IsPrimary -> "is-primary" 
  | IsMedium -> "is-medium" 
  | IsLoading false -> ""
  | IsLoading true -> "is-loading"
  | (* etc. *)

let bulma (classes: Bulma list) = 
   classes
   |> List.map toBulmaClass
   |> String.concat " "
   |> Class

let render state dispatch = 
  button [ bulma [ Button; IsPrimary ] ] [
    i [ Class "fa fa-plus" ] [ ]  
  ]  
```
What do you think of it?

**Comment by MangelMaxime** [comment]
> I expected to be able to use OnClick as part of button:

This is already possible. When it's obvious for an element that he needs to use a specific property we are adding it to the top level.

> I have been testing simpler alternative syntax that only applies classes, nothing more, something "Fulma lite":

You are just moving the nested list here. 

When using Fulma the nested list is about the "standard" HTMLProps.

When using "Fulma lite" the nested list is about the Fulma classes. 

So there isn't much benefit in doing Fulma lite.

To answer the original question

> Is it possible to combine *.Props into parent list?

When designing Fulma it was not possible to do it. Because F# doesn't do implicit cast.
For example, this is the reason why in some place of Fulma code you have `:> IHTMLProp` cast.

- [Example 1](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Common.fs#L449)
- [Example 2](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Elements/Button.fs#L95)

With v2 we made a huge rewrite to mutualize as much code as possible so we don't have a lot of these casts left.

I know that the implicit cast rules have been made less strict in the newer version of F#. But when I tested it it was not working properly perhaps it has been fixed since my test.

**Comment by MangelMaxime** [comment]
But if we can write:

```fs
Button.button [ Button.IsOutlined
                OnClick (fun _ -> ... ) ]
    [ str "My button" ]
```

instead of

```fs
Button.button [ Button.IsOutlined
                Button.OnClick (fun _ -> ... ) ]
    [ str "My button" ]
```

It could indeed be an improvement and make the API even more consistent.

One major problem if it proves possible and we choose to take the move. Is that people will have a bit (lot?) of work to do the conversion.

I am stating this "problem" just so we are all aware about it.

**Comment by Zaid-Ajaj** [comment]
> This is already possible. When it's obvious for an element that he needs to use a specific property we are adding it to the top level.

My bad, I thought I already tried that but it indeed works just fine! I really like it this way :smile: 

> So there isn't much benefit in doing Fulma lite.

Well, it is a lot closer to the documentation and a lot smaller than a full-fledged library, usually you only need the classes provided by Bulma. But for now, Fulma's API is good enough and doesn't need it

I think this is resolved, thanks a lot for your help!
