### ISSUE TITLE
Heading.IsTitle doesn't exist

### ISSUE THREAD

**Issue by johnmullany** [Fulma/Fulma#239]
The IsTitle doesn't seem to exist per the documentation in https://fulma.github.io/Fulma/#fulma/elements/title
I can get around it by using a different heading size. Is it supposed to exist or does the documentation need to be updated?

**Comment by MangelMaxime** [comment]
By default, all the `Heading.XX` have the `title` added to it. 

The documentation needs to be updated and there is actually a bug on [this line](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Elements/Heading.fs#L46) because the `RemoveClass("title")` does nothing, I guess the `baseClass` is added after the `RemoveClass` is called.

**Comment by MangelMaxime** [comment]
Released in version 2.6.0 and the doc is being updated
