### ISSUE TITLE
Documentation: Compatibility not always up to date

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#252]
Some libraries were upgraded to the latest version, but are still referencing older versions on the documentation website.

For example, there is a commit that says FontAwesome was updated to 5.12.1 but this is shown in the docs:

<img width="322" alt="Screenshot 2020-04-02 at 08 35 27" src="https://user-images.githubusercontent.com/2250570/78217738-ea316200-74bc-11ea-944d-d2acae0a45c5.png">

**Comment by kunjee17** [comment]
Long back. We decided to put versions there just to that version stays in sync. Seems to be that sync is broken. But all was manual task and I guess package json and package json lock version might very. If someone just did run `npm update`. 

AFAIK, all this is manual effort if @MangelMaxime  haven't automated it.

**Comment by MangelMaxime** [comment]
Yes, it has always been a manual task even if that could probably be updated.

**Comment by MangelMaxime** [comment]
Fulma supports Femto.

I am checking the Femto metadata, when done I will remove the version information from the documentation because it's hard to keep up to date.

Also, for Fable.FontAwesome you not only have to set it for Fable.FontAweomse but also Fable.FontAwesome.Free and Fable.FontAwesome.Pro which will be hard to display correctly.

I will choose the easy solution and ask people to use femto. :)
