### ISSUE TITLE
Bulma released v0.9.0 w/2 new features - RTL and spacing helpers

### ISSUE THREAD

**Issue by zakaluka** [Fulma/Fulma#259]
Looks like Bulma has released v0.9.0 with 2 new features: RTL support and Spacing helpers.  

Here is the changelog: https://github.com/jgthms/bulma/blob/master/CHANGELOG.md

Would it be possible to add this support to Fulma?

**Comment by MangelMaxime** [comment]
Hello, 

Yes, it is possible.

I think the last time I updated the supported version of Bulma it was for version 0.8.0 so we also need to upgrade for 0.8.1, 0.8.2 if there were any changes that impact Fulma.

I don't think they're anything to be done in Fulma in order to support RTL support feature. At least the changelog only speak about a SASS variable to set to true.

The spacing helpers should be added to the modifiers modules probably under with the following API:

```fs
Text.span [ Modifiers [ Modifier.Spacing (Spacing.MarginTop, Spacing.Is1)
                        Modifier.Spacing (Spacing.PaddingTopAndBottom, Spacing.Is2) ] ]
```

Would you like to give it a try?

**Comment by kerams** [comment]
There's only one addition between 0.8.0 and 0.9 as far as I can tell - light colors on `panel`.

**Comment by kerams** [comment]
Except for what @zakaluka said, there are also new color helpers https://bulma.io/documentation/helpers/color-helpers/

**Comment by zakaluka** [comment]
I am (slowly) trying to get this done.  Apologies for the slow pace, but free time has been hard to come by.

**Comment by MangelMaxime** [comment]
Hello @zakaluka ,

thank you for keeping us informed and taking the time to work on it.

Don't hesitate to tell us if you need help.
