### ISSUE TITLE
Datepicker rendering is broken

### ISSUE THREAD

**Issue by travis-leith** [Fulma/Fulma#267]
This is what my datepicker gets rendered as

![image](https://user-images.githubusercontent.com/29927084/89900112-5bfc8380-dbf4-11ea-9591-c0948bd78270.png)

Relevant code snippets are:

```F#
let model = {
    isPrincipal = mustBePrincipal
    couldBeSpouse = couldBeSpouse
    person = person
    listData = Map.empty
    datePickerState = {DatePicker.Types.defaultState with AutoClose = true; ShowDeleteButton = true}
  }

let simpleDatePicker labelText currentState currentDate msg dispatch =
  let pickerConfig =
    let x = (DatePicker.Types.defaultConfig msg)
    
    {x with DatePickerStyle = []} //I have tried the default config and also tried with empty style list, both same result
  
  //Field.div
  //  []
  //  [
  //    Label.label
  //      []
  //      [str labelText]
  //    Control.div
  //      []
  //      [
  //        DatePicker.View.root pickerConfig currentState (Some currentDate) dispatch
  //      ]
  //  ]

  DatePicker.View.root pickerConfig currentState (Some currentDate) dispatch //At first I had it wrapped in a field, then tried on it's own, same result.

let view (model : Model) (dispatch : Msg -> unit) =
  div
    []
    [
      //whole bunch of other elements
      simpleDatePicker "Date of Birth" model.datePickerState dob UpdateDateOfBirth dispatch
    ]
```

**Comment by travis-leith** [comment]
If need be, I can put together a 'minimal' reproducible example, as a modification to the client page of the SAFE template. Perhaps not quite minimal but should at least be easy to replicate.

**Comment by MangelMaxime** [comment]
Hello, which version of `bulma-calendar` are you using? 

We only support `0.1.7` and not the later ones because in the later ones the author decided to stop supporting it as a CSS only framework and expect the users to use it's JavaScript code to control the library.

You can check if you have the right dependencies version by using [femto](https://github.com/Zaid-Ajaj/Femto/). See the instructions on the [documentation](https://fulma.github.io/Fulma/#fulma-extensions/calendar)

**Comment by travis-leith** [comment]
Hi @MangelMaxime ,

I have run the femto tool and have run then suggested yarn commands.
My femto output is now

![image](https://user-images.githubusercontent.com/29927084/90502435-de3df800-e15e-11ea-852d-7506fa644631.png)

After rebuilding and running I get the same output as before.

Is there any other info needed to help diagnose this problem?

**Comment by MangelMaxime** [comment]
Did you important the `*.scss` file in your style file?

For example: [`@import "~bulma-calendar/calendar.sass";](https://github.com/Fulma/Fulma/blob/master/docs/scss/main.scss).

**Comment by travis-leith** [comment]
@MangelMaxime  Yes that solved it for me. Thank you.
Should this step be mentioned in the docs, or is this requirement considered general knowledge?

**Comment by MangelMaxime** [comment]
I always considered it a general knowledge because if you include a library you need to configure it.

But you are not the first person to have this problem. I guess we should add a mention on top of each package documentation.

Something like: 


- `paket add Fulma.Extensions.Wikiki.Calendar --project <your project>`
- Follow instructions from `dotnet femto yourProject.fsproj` - Femto documentation
- Include the library style in your application. See npm library documentation for more information

**Comment by travis-leith** [comment]
A bit more background into how I got here: I know F# from building analytical libraries that others use for various purposes. While I do build the occasional GUI (in WPF), that is usually someone else's job. I only picked up web app development because the safe template makes it so easy for anyone who knows F#. So for me (and people like me) the npm/yarn requirements are very foreign and explicit guidance is always welcome.
